// Code generated by github.com/light-speak/lighthouse, YOU CAN FUCKING EDIT BY YOURSELF.
package resolver

import (
  "github.com/light-speak/lighthouse/context"
  "fmt"
  "github.com/light-speak/lighthouse/graphql/excute"
)

func init() {
  excute.AddResolver("getTest", func(ctx *context.Context, args map[string]any) (interface{}, error) {
    id, ok := args["id"].(int64)
    if !ok {
      return nil, fmt.Errorf("argument: 'id' is not a int64, got %T", args["id"])
    }
    return GetTestResolver(ctx, id)
  })
}
