// Code generated by github.com/light-speak/lighthouse, YOU CAN FUCKING EDIT BY YOURSELF.
package resolver

import (
	"test/models"

	"github.com/light-speak/lighthouse/context"
	"github.com/light-speak/lighthouse/graphql/model"
)

func GetTestResolver(ctx *context.Context, id int64) (models.Test, error) {
	// Func:GetTest user code start. Do not remove this comment.
	test := models.Test{}
	db := model.GetDB()
	db.Where("id = ?", id).First(&test)
	return test, nil
	// Func:GetTest user code end. Do not remove this comment.
}
