// Code generated by github.com/light-speak/lighthouse, YOU CAN FUCKING EDIT BY YOURSELF.
package resolver

import (
  "test/models"
  "time"
  "github.com/light-speak/lighthouse/graphql/model"
  "github.com/light-speak/lighthouse/context"
)


func GetTestResolver(ctx *context.Context,id int64) (*models.Test, error) {
	// Func:GetTest user code start. Do not remove this comment.
	test := &models.Test{
		Model: model.Model{
			Id:        id,
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		Name:  "test",
		Email: "test@test.com",
	}
	return test, nil
	// Func:GetTest user code end. Do not remove this comment. 
}