// Code generated by github.com/light-speak/lighthouse, YOU CAN FUCKING EDIT BY YOURSELF.
package job

import (
	"fmt"
	"os"

	"github.com/light-speak/lighthouse/command"
	"github.com/light-speak/lighthouse/graphql/model/generate"
)

type Job struct{}

func (j *Job) Name() string {
	// Func:Name user code start. Do not remove this comment.
	return "generate:job"
	// Func:Name user code end. Do not remove this comment.
}

func (j *Job) Usage() string {
	// Func:Usage user code start. Do not remove this comment.
	return "generate job by lighthouse cli"
	// Func:Usage user code end. Do not remove this comment.
}

func (j *Job) Args() []*command.CommandArg {
	return []*command.CommandArg{
		// Func:Args user code start. Do not remove this comment.
		{
			Name:     "name",
			Type:     command.String,
			Usage:    "job name",
			Required: true,
		},
		// Func:Args user code end. Do not remove this comment.
	}
}

func (j *Job) Action() func(flagValues map[string]interface{}) error {
	return func(flagValues map[string]interface{}) error {
		// Func:Action user code start. Do not remove this comment.
		args, err := command.GetArgs(j.Args(), flagValues)
		if err != nil {
			return err
		}
		name, err := command.GetStringArg(args, "name")
		if err != nil {
			return err
		}
		if name == nil || *name == "" {
			return fmt.Errorf("job name is required and cannot be empty")
		}
		currentPath, err := os.Getwd()
		if err != nil {
			return err
		}
		err = generate.GenJob(*name, currentPath)
		if err != nil {
			return err
		}
		// Func:Action user code end. Do not remove this comment.
		return nil
	}
}

func (j *Job) OnExit() func() {
	return func() {}
}

// Section: user code section start. Do not remove this comment.
// Section: user code section end. Do not remove this comment.
