// Code generated by github.com/light-speak/lighthouse, YOU CAN FUCKING EDIT BY YOURSELF.
type QueueStart struct{}

func (q *QueueStart) Name() string {
	// Func:Name user code start. Do not remove this comment.
	return "queue:start"
	// Func:Name user code end. Do not remove this comment.
}

func (q *QueueStart) Usage() string {
	// Func:Usage user code start. Do not remove this comment.
	return "This is a command to Start the queue"
	// Func:Usage user code end. Do not remove this comment.
}

func (q *QueueStart) Args() []*command.CommandArg {
	return []*command.CommandArg{
		// Func:Args user code start. Do not remove this comment.
		// Func:Args user code end. Do not remove this comment.
	}
}

func (q *QueueStart) Action() func(flagValues map[string]interface{}) error {
	return func(flagValues map[string]interface{}) error {
		// Func:Action user code start. Do not remove this comment.
		queue.StartQueue()
		// Func:Action user code end. Do not remove this comment.
		return nil
	}
}

func (q *QueueStart) OnExit() func() {
	return func() {}
}

// Section: user code section start. Do not remove this comment.
// Section: user code section end. Do not remove this comment.
