// Code generated by github.com/light-speak/lighthouse, YOU CAN FUCKING EDIT BY YOURSELF.
package resolver

import (
  "github.com/light-speak/lighthouse/context"
  "user/models"
)


// CreatePost <nil>
// 
// Parameters:
// - input: <nil>
// 
// Returns:
// 
// - Post
func (r *Resolver) CreatePostResolver(ctx *context.Context,input *models.TestInput) (*models.Post, error) {
	// Func:CreatePost user code start. Do not remove this comment.
	return nil, nil
	// Func:CreatePost user code end. Do not remove this comment. 
}