// Code generated by github.com/light-speak/lighthouse, YOU CAN FUCKING EDIT BY YOURSELF.
package resolver

import (
  "user/models"
  "github.com/light-speak/lighthouse/context"
)


// CreatePost2 创建帖子2
// 
// Parameters:
// - age: 年龄
// - name: 用户名
// 
// Returns:
// 
// - *Post
func (r *Resolver) CreatePost2Resolver(ctx *context.Context,age *int64,name *string) (*models.Post, error) {
	// Func:CreatePost2 user code start. Do not remove this comment.
	return nil, nil
	// Func:CreatePost2 user code end. Do not remove this comment. 
}