// Code generated by github.com/light-speak/lighthouse, YOU CAN FUCKING EDIT BY YOURSELF.
package resolver

import (
  "errors"
  "fmt"
  "sync"
  "github.com/light-speak/lighthouse/context"
)


func (r *Resolver) FuckingAttrAttrResolver(ctx *context.Context, data *sync.Map) (string, error) {
	// Func:FuckingAttr user code start. Do not remove this comment.
	id, ok := data.Load("id")
	if !ok {
		return "", errors.New("id is not found")
	}
	return fmt.Sprintf("这是Attr, 传进来的data, ID: %v", id), nil
	// Func:FuckingAttr user code end. Do not remove this comment. 
}

// Section: user code section start. Do not remove this comment.



// Section: user code section end. Do not remove this comment. 
