// Code generated by github.com/light-speak/lighthouse, YOU CAN FUCKING EDIT BY YOURSELF.
package resolver

import (
  "github.com/light-speak/lighthouse/graphql/model"
  "github.com/light-speak/lighthouse/log"
  "user/models"
  "github.com/light-speak/lighthouse/context"
)


// GetPost <nil>
// 
// Parameters:
// - fuck: <nil>
// 
// Returns:
// 
// - Post
func (r *Resolver) GetPostResolver(ctx *context.Context,fuck string) (*models.Post, error) {
	// Func:GetPost user code start. Do not remove this comment.
	log.Debug().Msg("GetPostResolver")
	db := model.GetDB()
	post := &models.Post{}
	db.Where("id = ?", fuck).First(post)
	return post, nil
	// Func:GetPost user code end. Do not remove this comment. 
}