// Code generated by github.com/light-speak/lighthouse, YOU CAN FUCKING EDIT BY YOURSELF.
package resolver

import (
  "user/models"
  "github.com/light-speak/lighthouse/context"
  "github.com/light-speak/lighthouse/graphql/model"
)


// GetPosts <nil>
// 
// Parameters:
// - fuck: <nil>
// 
// Returns:
// 
// - []Post
func (r *Resolver) GetPostsResolver(ctx *context.Context,fuck string) ([]*models.Post, error) {
	// Func:GetPosts user code start. Do not remove this comment.
	posts := []*models.Post{}
	db := model.GetDB()
	db.Find(&posts)
	return posts, nil
	// Func:GetPosts user code end. Do not remove this comment. 
}