// Code generated by github.com/light-speak/lighthouse, YOU CAN FUCKING EDIT BY YOURSELF.
package resolver

import  "github.com/light-speak/lighthouse/context"


// GetPostIds <nil>
// 
// Parameters:
// 
// Returns:
// 
// - []int64
func (r *Resolver) GetPostIdsResolver(ctx *context.Context) ([]int64, error) {
	// Func:GetPostIds user code start. Do not remove this comment.
	return []int64{1, 2, 3}, nil
	// Func:GetPostIds user code end. Do not remove this comment. 
}