// Code generated by github.com/light-speak/lighthouse, YOU CAN FUCKING EDIT BY YOURSELF.
package resolver

import (
  "github.com/light-speak/lighthouse/context"
  "github.com/light-speak/lighthouse/log"
  "user/models"
)


// Me <nil>
// 
// Parameters:
// - id: <nil>
// 
// Returns:
// 
// - User
func (r *Resolver) MeResolver(ctx *context.Context,id *int64) (*models.User, error) {
	// Func:Me user code start. Do not remove this comment.
	log.Debug().Msgf("me: %+v", ctx)
	return nil, nil
	// Func:Me user code end. Do not remove this comment. 
}