// Code generated by github.com/light-speak/lighthouse, DO NOT EDIT.
package resolver

import (
  "github.com/light-speak/lighthouse/context"
  "user/models"
  "github.com/light-speak/lighthouse/graphql/excute"
  "fmt"
)

func init() {
  excute.AddResolver("getPost", func(ctx *context.Context, args map[string]any) (interface{}, error) {
    fuck, ok := args["fuck"].(string)
    if !ok {
      return nil, fmt.Errorf("argument: 'fuck' is not a string, got %T", args["fuck"])
    }
    return GetPostResolver(ctx, fuck)
  })
  excute.AddResolver("testPostEnum", func(ctx *context.Context, args map[string]any) (interface{}, error) {
    enumValue, ok := args["enum"].(int8)
    if !ok {
      return nil, fmt.Errorf("argument: 'enum' is not a int8, got %T", args["enum"])
    }
    enum := models.TestEnum(enumValue)
    return TestPostEnumResolver(ctx, enum)
  })
  excute.AddResolver("testPostInput", func(ctx *context.Context, args map[string]any) (interface{}, error) {
    input, ok := args["input"].(models.TestInput)
    if !ok {
      return nil, fmt.Errorf("argument: 'input' is not a models.TestInput, got %T", args["input"])
    }
    return TestPostInputResolver(ctx, input)
  })
}
