// Code generated by github.com/light-speak/lighthouse, YOU CAN FUCKING EDIT BY YOURSELF.
package resolver

import (
  "user/models"
  "github.com/light-speak/lighthouse/context"
)


// TestNullableEnum <nil>
// 
// Parameters:
// - enum: <nil>
// 
// Returns:
// 
// - string
func (r *Resolver) TestNullableEnumResolver(ctx *context.Context,enum *models.TestEnum) (string, error) {
	// Func:TestNullableEnum user code start. Do not remove this comment.
	panic("not implement")
	// Func:TestNullableEnum user code end. Do not remove this comment. 
}