// Code generated by github.com/light-speak/lighthouse, YOU CAN FUCKING EDIT BY YOURSELF.
package resolver

import (
	"user/models"

	"github.com/light-speak/lighthouse/context"
	"github.com/light-speak/lighthouse/log"
)

// TestInputList <nil>
//
// Parameters:
// - input: <nil>
//
// Returns:
//
// - []int64
func (r *Resolver) TestInputListResolver(ctx *context.Context, input []*models.TestInput) ([]int64, error) {
	// Func:TestInputList user code start. Do not remove this comment.
	log.Warn().Interface("input", input).Msg("test input list")
	return []int64{1, 2, 3}, nil
	// Func:TestInputList user code end. Do not remove this comment.
}
