// Code generated by github.com/light-speak/lighthouse, YOU CAN FUCKING EDIT BY YOURSELF.
package resolver

import (
  "github.com/light-speak/lighthouse/context"
  "github.com/light-speak/lighthouse/log"
  "user/models"
)


// TestPostId <nil>
// 
// Parameters:
// - id: <nil>
// 
// Returns:
// 
// - *Post
func (r *Resolver) TestPostIdResolver(ctx *context.Context,id int64) (*models.Post, error) {
	// Func:TestPostId user code start. Do not remove this comment.
	log.Debug().Msgf("id: %d", id)
	return nil, nil
	// Func:TestPostId user code end. Do not remove this comment. 
}