// Code generated by github.com/light-speak/lighthouse, YOU CAN FUCKING EDIT BY YOURSELF.
package resolver

import (
  "user/models"
  "github.com/light-speak/lighthouse/context"
)


// TestPostInt <nil>
// 
// Parameters:
// - id: <nil>
// 
// Returns:
// 
// - *Post
func (r *Resolver) TestPostIntResolver(ctx *context.Context,id bool) (*models.Post, error) {
	// Func:TestPostInt user code start. Do not remove this comment.
	return nil, nil
	// Func:TestPostInt user code end. Do not remove this comment. 
}