// Code generated by github.com/light-speak/lighthouse, YOU CAN FUCKING EDIT BY YOURSELF.
package resolver

import (
  "github.com/light-speak/lighthouse/log"
  "fmt"
  "user/models"
  "github.com/light-speak/lighthouse/context"
)


// TestPostEnum <nil>
// 
// Parameters:
// - enum: <nil>
// 
// Returns:
// 
// - string
func (r *Resolver) TestPostEnumResolver(ctx *context.Context,enum *models.TestEnum) (string, error) {
	// Func:TestPostEnum user code start. Do not remove this comment.
	log.Debug().Msgf("enum: %+v", enum)
	res := fmt.Sprintf("啥也不是！：%v", *enum == models.TestEnumA)
	return res, nil
	// Func:TestPostEnum user code end. Do not remove this comment. 
}