# 基本运行配置
run:
  timeout: 5m
  go: '1.23'
  modules-download-mode: readonly
  allow-parallel-runners: true
  skip-dirs:
    - vendor
    - third_party
    - internal
    - go/pkg/mod
    - usr/local/go/src

# 输出格式配置
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

# 启用的 linters
linters:
  disable-all: true
  enable:
    # 错误检查
    - errcheck     # 检查错误处理
    - gosec       # 安全性检查
    - govet       # Go 原生静态分析
    
    # 代码质量
    - gosimple    # 代码简化建议
    - staticcheck # 静态分析
    - unused      # 未使用的代码
    - ineffassign # 无效赋值
    
    # 代码风格
    - gofmt       # 格式化检查
    - goimports   # import 格式化
    - misspell    # 拼写检查
    - revive      # 代码风格检查

# linter 具体设置
linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/light-speak/lighthouse
  govet:
    check-shadowing: false
    enable-all: false
    disable:
      - fieldalignment
      - shadow
  revive:
    rules:
      - name: package-comments
        disabled: true
  staticcheck:
    go: "1.23"
    checks: ["all"]

# 问题处理规则
issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  
  # 排除规则
  exclude-rules:
    # 测试文件规则
    - path: _test\.go
      linters:
        - errcheck
        - revive
    
    # Go 1.23 特定问题
    - text: "cannot range over"
      linters: [typecheck]
    - text: "cannot infer"
      linters: [typecheck]
    - text: "undefined"
      linters: [typecheck]
    - text: "missing return"
      linters: [typecheck]
