# 基本运行配置
run:
  deadline: 5m
  tests: false
  skip-dirs:
    - vendor
    - third_party
    - internal
    - go/pkg/mod
    - /usr/local/go/src 
    - /opt/hostedtoolcache/go 

# 输出格式配置
output:
  format: colored-line-number

# 启用的 linters
linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - revive
  disable:
    - typecheck

# linter 具体设置
linters-settings:
  gofmt:
    simplify: true
  govet:
    check-shadowing: false
    enable-all: false
    disable:
      - fieldalignment
      - shadow
  revive:
    rules:
      - name: package-comments
        disabled: true
  staticcheck:
    go: "1.23"
    checks: ["all"]

# 问题处理规则
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec

  max-issues-per-linter: 0
  max-same-issues: 0
