run:
  timeout: 5m
  modules-download-mode: readonly
  skip-dirs-use-default: true
  go: '1.23'
  skip-dirs:
    - vendor
    - third_party
    - internal
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*\\.gen\\.go$"
    - ".*\\.mock\\.go$"
    - ".*\\.tpl$"
    - ".*_gen\\.go$"
  build-tags:
    - go1.23
  allow-parallel-runners: false

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/light-speak/lighthouse
  govet:
    check-shadowing: false
    enable-all: false
    disable:
      - fieldalignment
      - shadow
      - stdmethods
  staticcheck:
    go: "1.23"
    checks: ["all"]

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - revive
    - text: "cannot range over"
      linters:
        - typecheck
    - text: "cannot infer"
      linters:
        - typecheck
    - text: "undefined"
      linters:
        - typecheck
    - text: "missing return"
      linters:
        - typecheck
    - text: "not enough arguments"
      linters:
        - typecheck
    - text: "Lock"
      linters:
        - typecheck
    - text: "Unlock"
      linters:
        - typecheck
