// Code generated by Kitex v0.10.3. DO NOT EDIT.

package manor

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	rpc "github.com/light-speak/lighthouse/manor/kitex_gen/manor/rpc"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Register(ctx context.Context, req *rpc.RegisterRequest, callOptions ...callopt.Option) (r *rpc.RegisterResponse, err error)
	Ping(ctx context.Context, req *rpc.PingRequest, callOptions ...callopt.Option) (r *rpc.PingResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kManorClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kManorClient struct {
	*kClient
}

func (p *kManorClient) Register(ctx context.Context, req *rpc.RegisterRequest, callOptions ...callopt.Option) (r *rpc.RegisterResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Register(ctx, req)
}

func (p *kManorClient) Ping(ctx context.Context, req *rpc.PingRequest, callOptions ...callopt.Option) (r *rpc.PingResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Ping(ctx, req)
}
