// Code generated by Kitex v0.10.3. DO NOT EDIT.

package manor

import (
	server "github.com/cloudwego/kitex/server"
	rpc "github.com/light-speak/lighthouse/manor/kitex_gen/manor/rpc"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler rpc.Manor, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
