// Code generated by Kitex v0.10.3. DO NOT EDIT.

package manor

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	rpc "github.com/light-speak/lighthouse/manor/kitex_gen/manor/rpc"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Register": kitex.NewMethodInfo(
		registerHandler,
		newManorRegisterArgs,
		newManorRegisterResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Ping": kitex.NewMethodInfo(
		pingHandler,
		newManorPingArgs,
		newManorPingResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	manorServiceInfo                = NewServiceInfo()
	manorServiceInfoForClient       = NewServiceInfoForClient()
	manorServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return manorServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return manorServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return manorServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "Manor"
	handlerType := (*rpc.Manor)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "rpc",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.10.3",
		Extra:           extra,
	}
	return svcInfo
}

func registerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*rpc.ManorRegisterArgs)
	realResult := result.(*rpc.ManorRegisterResult)
	success, err := handler.(rpc.Manor).Register(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newManorRegisterArgs() interface{} {
	return rpc.NewManorRegisterArgs()
}

func newManorRegisterResult() interface{} {
	return rpc.NewManorRegisterResult()
}

func pingHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*rpc.ManorPingArgs)
	realResult := result.(*rpc.ManorPingResult)
	success, err := handler.(rpc.Manor).Ping(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newManorPingArgs() interface{} {
	return rpc.NewManorPingArgs()
}

func newManorPingResult() interface{} {
	return rpc.NewManorPingResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Register(ctx context.Context, req *rpc.RegisterRequest) (r *rpc.RegisterResponse, err error) {
	var _args rpc.ManorRegisterArgs
	_args.Req = req
	var _result rpc.ManorRegisterResult
	if err = p.c.Call(ctx, "Register", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Ping(ctx context.Context, req *rpc.PingRequest) (r *rpc.PingResponse, err error) {
	var _args rpc.ManorPingArgs
	_args.Req = req
	var _result rpc.ManorPingResult
	if err = p.c.Call(ctx, "Ping", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
