// Code generated by Kitex v0.10.3. DO NOT EDIT.
package manor

import (
	server "github.com/cloudwego/kitex/server"
	rpc "github.com/light-speak/lighthouse/manor/kitex_gen/manor/rpc"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler rpc.Manor, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler rpc.Manor, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
