// Code generated by github.com/light-speak/lighthouse, DO NOT EDIT.
package models




type SortOrder int8

const (
  ASC SortOrder = 1
  DESC SortOrder = -1
)

func (e SortOrder) ToString() string {
  switch e {
  case ASC:
    return "ASC"
  case DESC:
    return "DESC"
  default:
    return "unknown"
  }
}

var SortOrderMap = map[string]SortOrder{
  "ASC": ASC,
  "DESC": DESC,
}
