// Code generated by github.com/light-speak/lighthouse, DO NOT EDIT.
package models

import  "github.com/light-speak/lighthouse/graphql/model"


type Test struct {
  model.Model
  Email string `gorm:"type:varchar(255)" json:"email" `
  Name string `json:"name" gorm:"type:varchar(255)" `
}

func (*Test) IsModel() bool { return true }
func (*Test) TableName() string { return "tests" }
func (*Test) TypeName() string { return "test" }


func Migrate() error {
	return model.GetDB().AutoMigrate(
    &Test{},
  )
}