// Code generated by github.com/light-speak/lighthouse, DO NOT EDIT.
package models




type SortOrder int8

const (
  // The ASC enum value represents ascending order.
  SortOrderASC SortOrder = 1
  // The DESC enum value represents descending order.
  SortOrderDESC SortOrder = -1
)

func (e SortOrder) ToString() string {
  switch e {
  case SortOrderASC:
    return "ASC"
  case SortOrderDESC:
    return "DESC"
  default:
    return "unknown"
  }
}

var SortOrderMap = map[string]SortOrder{
  "ASC": SortOrderASC,
  "DESC": SortOrderDESC,
}
