// Code generated by github.com/light-speak/lighthouse, DO NOT EDIT.
package models

import  "github.com/light-speak/lighthouse/graphql/model"


type Author struct {
  model.Model
  Name string `json:"name" gorm:"type:varchar(255)" `
}

func (*Author) IsModel() bool { return true }
func (*Author) TableName() string { return "authors" }
func (*Author) TypeName() string { return "author" }
func AuthorEnumFields(key string) func(interface{}) interface{} {
  return nil
}


func Migrate() error {
	return model.GetDB().AutoMigrate(
    &Author{},
  )
}