// Code generated by github.com/light-speak/lighthouse, DO NOT EDIT.
package models




type LoginResponse struct {
  Token string `gorm:"type:varchar(255)" json:"token" `
  Authorization string `json:"authorization" gorm:"type:varchar(255)" `
  Author *Author `json:"author" `
}
