// Code generated by github.com/light-speak/lighthouse, YOU CAN FUCKING EDIT BY YOURSELF.
package initialize

import (
	"github.com/light-speak/lighthouse/command"
	"github.com/light-speak/lighthouse/command/cli/generate/initialize/one"
)

type Initialize struct{}

func (c *Initialize) Name() string {
	// Func:Name user code start. Do not remove this comment.
	return "generate:init"
	// Func:Name user code end. Do not remove this comment.
}

func (c *Initialize) Usage() string {
	// Func:Usage user code start. Do not remove this comment.
	return "Create a new lighthouse project"
	// Func:Usage user code end. Do not remove this comment.
}

func (c *Initialize) Args() []*command.CommandArg {
	return []*command.CommandArg{
		// Func:Args user code start. Do not remove this comment.
		{
			Name:     "module",
			Type:     command.String,
			Required: true,
			Usage:    "Project module name like github.com/light-speak/lighthouse",
		},
		// Func:Args user code end. Do not remove this comment.
	}
}

func (c *Initialize) Action() func(flagValues map[string]interface{}) error {
	return func(flagValues map[string]interface{}) error {
		// Func:Action user code start. Do not remove this comment.
		args, err := command.GetArgs(c.Args(), flagValues)
		if err != nil {
			return err
		}
		module, err := command.GetStringArg(args, "module")
		if err != nil {
			return err
		}
		err = one.Run(*module)
		if err != nil {
			return err
		}
		// Func:Action user code end. Do not remove this comment.
		return nil
	}
}

// Section: user code section start. Do not remove this comment.
// Section: user code section end. Do not remove this comment.
