// Code generated by github.com/light-speak/lighthouse, YOU CAN FUCKING EDIT BY YOURSELF.
package service

import (
  _ "test/resolver"
  _ "test/repo"
  _ "test/models"
  "github.com/light-speak/lighthouse/handler"
)

func StartService() {
	handler.StartService()
}
