// Code generated by github.com/light-speak/lighthouse, DO NOT EDIT.

package generate

import (
	"gorm.io/gorm"
	"time"
	"user/graph/models"
)

func GetUserLoader(db *gorm.DB) *UserLoader {
    return &UserLoader{
        maxBatch: 100,
        wait:     1 * time.Millisecond,
        fetch: func(ids []int64) ([]*models.User, []error) {
            var users []*models.User
            if err := db.Find(&users, ids).Error; err != nil {
                return nil, nil
            }
            userById := map[int64]*models.User{}
            for _, user:= range users {userById[user.ID] =user}

            result := make([]*models.User, len(ids))
            for i, id := range ids {
                result[i] =userById[id]
                i++
            }
            return result, nil
        },
    }
}
