// Code generated by github.com/light-speak/lighthouse, DO NOT EDIT.

package models

import (
	"context"
	"gorm.io/gorm"
)


func PostScopePublished(ctx context.Context, values ...string) func(tx *gorm.DB) *gorm.DB {
	return func(tx *gorm.DB) *gorm.DB {
		return tx
	}
}
