// Code generated by github.com/light-speak/lighthouse, YOU CAN FUCKING EDIT BY YOURSELF.
package start

import (
	"user/service"

	"github.com/light-speak/lighthouse/command"
	"github.com/light-speak/lighthouse/log"
)


type Start struct {}

func (c *Start) Name() string {
	// Func:Name user code start. Do not remove this comment. 
	return "app:start"
	// Func:Name user code end. Do not remove this comment. 
}

func (c *Start) Usage() string {
	// Func:Usage user code start. Do not remove this comment. 
	return "This is a command generated by lighthouse cli"
	// Func:Usage user code end. Do not remove this comment. 
}

func (c *Start) Args() []*command.CommandArg {
	return []*command.CommandArg{
		// Func:Args user code start. Do not remove this comment. 
		// Func:Args user code end. Do not remove this comment. 
	}
}

func (c *Start) Action() func(flagValues map[string]interface{}) error {
	return func(flagValues map[string]interface{}) error {
		// Func:Action user code start. Do not remove this comment. 
		args, err := command.GetArgs(c.Args(), flagValues)
		if err != nil {
			return err
		}
		log.Info().Msgf("args: %v", args)
		service.StartService()
		// Func:Action user code end. Do not remove this comment. 
		return nil
	}
}

func (c *Start) OnExit() func() {
	return func() {}
}

// Section: user code section start. Do not remove this comment. 
// Section: user code section end. Do not remove this comment. 
