// Code generated by github.com/light-speak/lighthouse, YOU CAN FUCKING EDIT BY YOURSELF.
package service

import (
	_ "example/author/models"
	_ "example/author/repo"
	"example/author/resolver"
	_ "example/author/resolver"

	"github.com/light-speak/lighthouse/handler"
)

func StartService() {
	handler.StartService(&resolver.Resolver{})
}
