// Code generated by github.com/light-speak/lighthouse, YOU CAN FUCKING EDIT BY YOURSELF.
module user

go 1.23.1

replace github.com/light-speak/lighthouse => ../../

require github.com/light-speak/lighthouse v0.0.1
