// Code generated by github.com/light-speak/lighthouse, YOU CAN FUCKING EDIT BY YOURSELF.
package main

import (
	"fmt"
	"os"
	"user/cmd"
	_ "user/resolver"

	"github.com/light-speak/lighthouse/command"
)

func main() {
	cmd := &cmd.Command{}
	if err := command.Run(cmd, os.Args); err != nil {
		fmt.Fprintf(os.Stderr, "error: %s\n", err)
		os.Exit(1)
	}
}
