// Code generated by github.com/light-speak/lighthouse, DO NOT EDIT.
package models




type SortOrder int8

const (
  ASC SortOrder = 1
  DESC SortOrder = -1
)
type TestEnum int8

const (
  A TestEnum = 1
  B TestEnum = 2
)
type TestEnum2 int8

const (
  A2 TestEnum2 = iota
  B2
)
