// Code generated by github.com/light-speak/lighthouse, DO NOT EDIT.
package models




type Userable interface {
  IsUserable()
  GetUser() User
  GetUserId() int64
}

type HasName interface {
  IsHasName()
  GetName() string
}

type Commentable interface {
  IsCommentable()
}
