// Code generated by github.com/light-speak/lighthouse, DO NOT EDIT.
package models

type HasName interface {
	IsHasName()
	GetName() string
}

type Userable interface {
	IsUserable()
	GetUser() User
	GetUserId() int64
}

type Commentable interface {
	IsCommentable()
}
