// Code generated by github.com/light-speak/lighthouse, DO NOT EDIT.
package models

import (
	"github.com/light-speak/lighthouse/graphql/model"
)


type User struct {
  model.Model
  Name string `json:"name" gorm:"index" `
  Posts []*Post `json:"posts" gorm:"-"`
}

func (*User) IsModel() bool { return true }
func (*User) IsHasName() bool { return true }
func (this *User) GetName() string { return this.Name }


type Post struct {
  model.Model
  Title string `json:"title" gorm:"index" `
  Content string `json:"content" `
  UserId int64 `json:"userId" gorm:"index" `
  User User `json:"user" `
}

func (*Post) IsModel() bool { return true }


func Migrate() error {
	err := model.GetDB().AutoMigrate(
		&User{},
    &Post{},
  )
  if err != nil {
    return err
  }
  return nil
}
