// Code generated by github.com/light-speak/lighthouse, DO NOT EDIT.
package models

import  "github.com/light-speak/lighthouse/graphql/model"


type UserPaginateResponse struct {
  Data []User 
  PaginateInfo model.PaginateInfo 
  
}

type PostPaginateResponse struct {
  Data []Post 
  PaginateInfo model.PaginateInfo 
  
}
