// Code generated by github.com/light-speak/lighthouse, YOU CAN FUCKING EDIT BY YOURSELF.
package cmd

import "github.com/light-speak/lighthouse/lightcmd/queue"

type InitQueue struct{}

func (c *InitQueue) Name() string {
	// Func:Name user code start. Do not remove this comment.
	return "queue:init"
	// Func:Name user code end. Do not remove this comment.
}

func (c *InitQueue) Usage() string {
	// Func:Usage user code start. Do not remove this comment.
	return "install queue service in project"
	// Func:Usage user code end. Do not remove this comment.
}

func (c *InitQueue) Args() []*CommandArg {
	return []*CommandArg{
		// Func:Args user code start. Do not remove this comment.
		// Func:Args user code end. Do not remove this comment.
	}
}

func (c *InitQueue) Action() func(flagValues map[string]interface{}) error {
	return func(flagValues map[string]interface{}) error {
		// Func:Action user code start. Do not remove this comment.
		return queue.InitQueue()
		// Func:Action user code end. Do not remove this comment.
	}
}

func (c *InitQueue) OnExit() func() {
	return func() {
		// Func:OnExit user code start. Do not remove this comment.
		// Func:OnExit user code end. Do not remove this comment.
	}
}

func init() {
	AddCommand(&InitQueue{})
}

// Section: user code section start. Do not remove this comment.
// Section: user code section end. Do not remove this comment.
