// Code generated by Kitex v0.11.3. DO NOT EDIT.
package searchservice

import (
	server "github.com/cloudwego/kitex/server"
	search "search/kitex_gen/search"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler search.SearchService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler search.SearchService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
