// Code generated by github.com/light-speak/lighthouse, YOU CAN FUCKING EDIT BY YOURSELF.
package resolver

import (
  "github.com/light-speak/lighthouse/graphql/model"
  "example/author/models"
  "github.com/light-speak/lighthouse/auth"
  "github.com/light-speak/lighthouse/context"
)


// Login <nil>
// 
// Parameters:
// - name: <nil>
// 
// Returns:
// 
// - LoginResponse
func (r *Resolver) LoginResolver(ctx *context.Context,name string) (*models.LoginResponse, error) {
	// Func:Login user code start. Do not remove this comment.
	db := model.GetDB()
	author := &models.Author{}
	err := db.Where("name = ?", name).First(author).Error
	if err != nil {
		return nil, err
	}
	token, err := auth.GetToken(author.Id)
	if err != nil {
		return nil, err
	}
	return &models.LoginResponse{
		Token:         token,
		Authorization: "Bearer " + token,
		Author:        author,
	}, nil
	// Func:Login user code end. Do not remove this comment. 
}