// Code generated by github.com/light-speak/lighthouse, DO NOT EDIT.

package generate

import (
	"gorm.io/gorm"
	"time"
	"post/graph/models"
)

func GetPostLoader(db *gorm.DB) *PostLoader {
    return &PostLoader{
        maxBatch: 100,
        wait:     1 * time.Millisecond,
        fetch: func(ids []int64) ([]*models.Post, []error) {
            var posts []*models.Post
            if err := db.Find(&posts, ids).Error; err != nil {
                return nil, nil
            }
            postById := map[int64]*models.Post{}
            for _, post:= range posts {postById[post.ID] =post}

            result := make([]*models.Post, len(ids))
            for i, id := range ids {
                result[i] =postById[id]
                i++
            }
            return result, nil
        },
    }
}
