{{ $structName := (.Name | ucFirst) }}
type {{ $structName }} struct {}

func (c *{{ $structName }}) Name() string {
	{{ userCodeStart "Name" }}
	return "{{.Scope | lcFirst}}:{{.Name | lcFirst}}"
	{{ userCodeEnd "Name" }}
}

func (c *{{ $structName }}) Usage() string {
	{{ userCodeStart "Usage" }}
	return "This is a command generated by light-cmd"
	{{ userCodeEnd "Usage" }}
}

func (c *{{ $structName }}) Args() []*cmd.CommandArg {
	return []*cmd.CommandArg{
		{{ userCodeStart "Args" }}
		{{ userCodeEnd "Args" }}
	}
}

func (c *{{ $structName }}) Action() func(flagValues map[string]interface{}) error {
	return func(flagValues map[string]interface{}) error {
		{{ userCodeStart "Action" }}
		args, err := cmd.GetArgs(c.Args(), flagValues)
		if err != nil {
			return err
		}
		lightlog.Info().Msgf("args: %v", args)
		{{ userCodeEnd "Action" }}
		return nil
	}
}

func (c *{{ $structName }}) OnExit() func() {
	return func() {
		{{ userCodeStart "OnExit" }}
		{{ userCodeEnd "OnExit" }}
	}
}

func init() {
	AddCommand(&{{ $structName }}{})
}

{{ userCodeSection }}


