// Code generated by github.com/light-speak/lighthouse, DO NOT EDIT.
package models

import  "github.com/light-speak/lighthouse/graphql/model"


type Work struct {
  model.ModelSoftDelete
  Name string `json:"name" gorm:"type:varchar(255)" `
  AuthorId int64 `json:"author_id" `
  Author *Author `json:"author" gorm:"-" `
}

func (*Work) IsModel() bool { return true }
func (*Work) TableName() string { return "works" }
func (*Work) TypeName() string { return "work" }
func WorkEnumFields(key string) func(interface{}) interface{} {
  return nil
}


func Migrate() error {
	return model.GetDB().AutoMigrate(
      &Work{},
  )
}