package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.53

import (
	"context"
	"fmt"
	"post/graph/generate"
	"post/graph/models"
)

// FindPostByID is the resolver for the findPostByID field.
func (r *entityResolver) FindPostByID(ctx context.Context, id int64) (*models.Post, error) {
	panic(fmt.Errorf("not implemented: FindPostByID - findPostByID"))
}

// FindUserByID is the resolver for the findUserByID field.
func (r *entityResolver) FindUserByID(ctx context.Context, id int64) (*models.User, error) {
	panic(fmt.Errorf("not implemented: FindUserByID - findUserByID"))
}

// Entity returns generate.EntityResolver implementation.
func (r *Resolver) Entity() generate.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
