// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"time"

	"github.com/light-speak/lighthouse/db"
)

type BaseModel interface {
	IsBaseModel()
	GetID() int64
	GetCreatedAt() time.Time
	GetUpdatedAt() time.Time
}

type BaseModelSoftDelete interface {
	IsBaseModelSoftDelete()
	GetID() int64
	GetCreatedAt() time.Time
	GetUpdatedAt() time.Time
	GetDeletedAt() *time.Time
}

type User struct {
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
	DeletedAt *time.Time `json:"deletedAt,omitempty"`
	Name      string     `json:"name"`
	Email     string     `json:"email"`
	// Custom GORM Model
	db.ModelSoftDelete `gorm:"embedded"`
}

func (User) IsBaseModelSoftDelete()        {}
func (this User) GetID() int64             { return this.ID }
func (this User) GetCreatedAt() time.Time  { return this.CreatedAt }
func (this User) GetUpdatedAt() time.Time  { return this.UpdatedAt }
func (this User) GetDeletedAt() *time.Time { return this.DeletedAt }

func (User) IsEntity() {}

func init() {
	db.Init()
	db.GetDb().AutoMigrate(

		&User{},
	)
}
