name: Lint and Style Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint and Style Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.1'
          cache: false

      - name: Install dependencies
        run: |
          go clean -modcache
          go mod download
          go mod tidy
          go mod verify
          go list -m all

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.0

      - name: Run golangci-lint
        run: |
          golangci-lint run --timeout=5m \
            --skip-files=".*\\.pb\\.go$,.*\\.gen\\.go$,.*\\.mock\\.go$,.*\\.tpl$,.*_gen\\.go$" \
            --modules-download-mode=readonly \
            ./...
