name: Code Quality Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint and Style Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.1'
          cache: true
          check-latest: true

      - name: Initialize Go module
        run: |
          go version
          go mod download
          go mod verify

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | \
          sh -s -- -b $(go env GOPATH)/bin v1.55.0
          golangci-lint version

      - name: Run linters
        run: |
          golangci-lint run \
            --timeout=5m \
            --out-format=colored-line-number \
            --max-same-issues=0 \
            --max-issues-per-linter=0 \
            ./...